#!/bin/sh

# Set these paths appropriately

BIN=/Users/sirasawa/Linux/tt/bin
CMD=/Users/sirasawa/Linux/tt/cmd
LIB=/Users/sirasawa/Linux/tt/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/danish-abbreviations-utf8
PARFILE=${LIB}/danish-utf8.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
