#!/bin/sh

# Set these paths appropriately

BIN=/Users/sirasawa/Linux/tt/bin
CMD=/Users/sirasawa/Linux/tt/cmd
LIB=/Users/sirasawa/Linux/tt/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
