#!/bin/sh

# Set these paths appropriately

BIN=/Users/sirasawa/Linux/tt/bin
CMD=/Users/sirasawa/Linux/tt/cmd
LIB=/Users/sirasawa/Linux/tt/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
