#!/bin/sh

# Set these paths appropriately

BIN=/Users/sirasawa/Linux/tt/bin
CMD=/Users/sirasawa/Linux/tt/cmd
LIB=/Users/sirasawa/Linux/tt/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
